# Generated by Django 5.2.12 on 2026-06-02 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_newsarticle_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image_url',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='newssource',
            name='default_category',
            field=models.ForeignKey(blank=True, help_text='Articles imported from this source default to this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='api.category'),
        ),
        migrations.AddField(
            model_name='newssource',
            name='feed_type',
            field=models.CharField(choices=[('rss', 'RSS / Atom feed'), ('newsdata', 'NewsData.io API'), ('manual', 'Manual / CMS only')], default='rss', max_length=20),
        ),
        migrations.AddField(
            model_name='newssource',
            name='last_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='api_endpoint',
            field=models.URLField(blank=True, help_text='RSS/feed or public news API URL'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['external_url'], name='api_newsart_externa_3c18cb_idx'),
        ),
    ]
