# Generated by Django 5.2.12 on 2026-06-02 16:04

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations
from django.contrib.postgres.search import SearchVector


def backfill_search_vector(apps, schema_editor):
    """Populate search_vector for all existing articles (one bulk UPDATE)."""
    NewsArticle = apps.get_model("api", "NewsArticle")
    NewsArticle.objects.update(
        search_vector=(
            SearchVector("title", weight="A", config="english")
            + SearchVector("summary", weight="B", config="english")
            + SearchVector("content", weight="C", config="english")
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_newsarticle_image_url_newssource_default_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='news_search_vector_gin'),
        ),
        migrations.RunPython(backfill_search_vector, migrations.RunPython.noop),
    ]
