# Generated by Django 5.2.12 on 2026-06-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_newsarticle_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='etag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newssource',
            name='last_modified',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
