# Generated by Django 5.2.12 on 2026-06-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_newssource_etag_newssource_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='external_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
