from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView, TokenVerifyView
from .views import (
    CategoryViewSet,
    NewsArticleViewSet,
    NewsSourceViewSet,
    AdminUserViewSet,
    AdminStatsView,
    ImportNewsView,
    SuperAdminTokenObtainPairView,
    UserTokenObtainPairView,
    RegisterView,
)

router = DefaultRouter()
router.register(r"categories", CategoryViewSet, basename="category")
# basename required because NewsArticleViewSet uses get_queryset() only (no class queryset)
router.register(r"news", NewsArticleViewSet, basename="news")
router.register(r"sources", NewsSourceViewSet, basename="source")
router.register(r"admin/users", AdminUserViewSet, basename="admin-user")

urlpatterns = [
    # ── Auth endpoints ────────────────────────────────────────────────────
    # Public: register a new regular user account
    path("auth/register/",    RegisterView.as_view(),               name="auth-register"),
    # Public: obtain JWT token for any active user
    path("auth/login/",       UserTokenObtainPairView.as_view(),    name="auth-login"),
    # Admin-only: obtain JWT token (superuser required)
    path("auth/admin/login/", SuperAdminTokenObtainPairView.as_view(), name="auth-admin-login"),
    # Token lifecycle
    path("auth/refresh/",     TokenRefreshView.as_view(),           name="auth-refresh"),
    path("auth/verify/",      TokenVerifyView.as_view(),            name="auth-verify"),

    # Admin dashboard statistics
    path("admin/stats/",       AdminStatsView.as_view(),            name="admin-stats"),
    # Admin: trigger news aggregation on demand
    path("admin/import-news/", ImportNewsView.as_view(),            name="admin-import-news"),

    # ── REST resource routes (generated by router) ────────────────────────
    path("", include(router.urls)),
]
